inputs:
  version:
    type: string
    required: true
outputs:
  result:
    value: ${{ steps.changelog.outputs.changelog }}
runs:
  using: "composite"
  steps:
    # CHANGELOG.mdの内容を取得
    - name: Get changelog
      run: |
        {
          echo 'changelog<<EOF'
          sed -n '/## ${{ inputs.version }}/,/^## /p' CHANGELOG.md | sed -e 1d -e '$d'
          echo EOF
        } >> $GITHUB_OUTPUT
      id: changelog
      shell: bash
