outputs:
  current_version:
    value: ${{ steps.get_current_version.outputs.current_version }}
  target_version:
    value: ${{ steps.next_target_version.outputs.result }}
runs:
  using: "composite"
  steps:
    # jqでpackage.jsonから現在のバージョンを取得
    - name: Get current version
      run: |
        jq -r '.version' package.json
        echo "current_version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
      id: get_current_version
      shell: bash
