runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: git config
      run: |
        git config --local user.email "${{ inputs.user }}@users.noreply.github.com"
        git config --local user.name "${{ inputs.user }}"
      shell: bash
    # pr_numberからPR情報を取得
    - name: Get PR
      run: |
        pr_json=$(gh pr view ${{ inputs.pr_number }} --json isDraft,headRefName)
        echo "pr_is_draft=$(echo $pr_json | jq -r '.isDraft')" >> $GITHUB_OUTPUT
        echo "pr_head_ref=$(echo $pr_json | jq -r '.headRefName')" >> $GITHUB_OUTPUT
      id: get_pr
      shell: bash
    # checkout PR
    - uses: actions/checkout@v4
      with:
        ref: ${{ steps.get_pr.outputs.pr_head_ref }}
      shell: bash
    # jqでpackage.jsonから現在のバージョンを取得
    - name: Get current version
      run: |
        jq -r '.version' package.json
        echo "current_version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
      id: get_current_version
      shell: bash
    # current_versionを加工してtarget_versionを取得
    - name: Get target version
      uses: actions/script@v7
      env:
        CURRENT_VERSION: ${{ steps.get_current_version.outputs.current_version }}
      with:
        script: |
          return process.env.CURRENT_VERSION.split('-')[0];
        result-encoding: string
      id: next_target_version
      shell: bash