inputs:
  pr_number:
    type: string
    description: "PR number"
    required: true
  user:
    type: string
    description: "user name"
    required: true
runs:
  using: "composite"
  steps:
    - name: git config
      run: |
        git config --local user.email "${{ inputs.user }}@users.noreply.github.com"
        git config --local user.name "${{ inputs.user }}"
      shell: bash
    # pr_numberからPR情報を取得
    - name: Get PR
      run: |
        pr_json=$(gh pr view ${{ inputs.pr_number }} --json isDraft,headRefName)
        echo "pr_is_draft=$(echo $pr_json | jq -r '.isDraft')" >> $GITHUB_OUTPUT
        echo "pr_head_ref=$(echo $pr_json | jq -r '.headRefName')" >> $GITHUB_OUTPUT
      id: get_pr
      shell: bash
    # checkout PR
    - uses: actions/checkout@v4
      with:
        ref: ${{ steps.get_pr.outputs.pr_head_ref }}
