on:
  workflow_call:
    inputs:
      pr_number:
        type: string
        description: PR number
        required: true
      main:
        type: string
        description: Main branch name
        default: main
      user:
        type: string
        description: User name
        default: github-actions[bot]

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: "Release Manager"

jobs:
  merge:
    name: "Go Merge"
    runs-on: ubuntu-latest
    if: ${{ inputs.pr_number != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Initialize
        uses: ./.github/actions/checkout-pr
        with:
          pr_number: ${{ inputs.pr_number }}
          user: ${{ inputs.user }}
      - name: Get Target Version
        uses: ./.github/actions/get-target-version
        id: v

      # バージョンをpackage.jsonに書き込み
      - name: Write version
        uses: ./.github/actions/rewrite-package-json
        with:
          version: ${{ steps.v.outputs.target_version }}

      # release/ブランチとタグを作成
      - name: Commit version
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git commit -am "[skip ci] Release: ${{ steps.v.outputs.target_version }}"
            git push origin HEAD:release/${{ steps.v.outputs.target_version }}
          fi

      - name: Try Merge
        run: |
          gh pr merge ${{ inputs.pr_number }} --merge --auto

      # CHANGELOG.mdの内容を取得
      - name: Get changelog
        uses: ./.github/actions/get-changelog
        with:
          version: ${{ steps.v.outputs.target_version }}
        id: changelog

      - name: Create tag
        run: |
          git tag "${{ steps.v.outputs.target_version }}"
          git push origin "${{ steps.v.outputs.target_version }}"

      # リリースを作成
      - name: Create release
        run: |
          gh release create "${{ steps.v.outputs.target_version }}" --title "${{ steps.v.outputs.target_version }}" --notes "${{ steps.changelog.outputs.changelog }}"

      # CHANGELOG.mdにUnreleasedのテンプレートを追加
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.main }}
      - name: Prepend CHANGELOG template
        env:
          CHANGES_TEMPLATE: |
            ## 202x.x.x (Unreleased)

            ### General
            -
            
            ### Client
            -
            
            ### Server
            -
            
        run: sed -i "1i $(echo "${CHANGES_TEMPLATE}" | sed -r 's/$/\\n/' | while IFS= read -r line; do echo -n "$line"; done)" CHANGELOG.md
      - name: Commit version
        run: |
          git commit -am "[skip ci] Update CHANGELOG.md (prepend template)"
          git push origin HEAD:${{ inputs.main }}
