on:
  pull_request:
    types: [ready_for_review]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: "Release Manager: release RC when ready for review"

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.get_pr.outputs.ref }}
    steps:
      - uses: actions/checkout@v4
      # PR情報を取得
      - name: Get PR
        run: |
          PR_JSON=$(gh pr view ${{ github.event.pull_request.number }} --json isDraft,headRefName)
          echo "ref=$(echo $PR_JSON | jq -r '.headRefName')" >> $GITHUB_OUTPUT
        id: get_pr
  release:
    uses: ./.github/workflows/dispatch-prerelease.yml
    needs: check
    if: startsWith(needs.check.outputs.ref, 'release/')
    permissions:
      contents: write
      issues: write
      pull-requests: write
    with:
      pr_number: ${{ github.event.pull_request.number }}
      user: 'LuckyBeast'
