name: "Release Manager: sync changelog with PR"

on:
  push:
    branches:
      - release/**
    paths:
      - 'CHANGELOG.md'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  edit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # headがrelease/かつopenのPRを1つ取得
      - name: Get PRs
        run: |
          echo "pr_number=$(gh pr list --limit 1 --head "${{ github.ref_name }}" --json number  --jq '.[] | .number')" >> $GITHUB_OUTPUT
        id: get_pr
      # jqでpackage.jsonから現在のバージョンを取得
      - name: Get current version
        run: |
          jq -r '.version' package.json
          echo "current_version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
        id: get_current_version
      # current_versionを加工してtarget_versionを取得
      - name: Get target version
        uses: actions/script@v7
        env:
          CURRENT_VERSION: ${{ steps.get_current_version.outputs.current_version }}
        with:
          script: |
            return process.env.CURRENT_VERSION.split('-')[0];
          result-encoding: string
        id: next_target_version
      # CHANGELOG.mdの内容を取得
      - name: Get changelog
        run: |
          {
            echo 'changelog<<EOF'
            sed -n '/## ${{ steps.next_target_version.outputs.result }}/,/^## /p' CHANGELOG.md | sed -e 1d -e '$d'
            echo EOF
          } >> $GITHUB_OUTPUT
        id: changelog
      # PRのnotesを更新
      - name: Update PR
        run: |
          gh pr edit ${{ steps.get_pr.outputs.pr_number }} --body "${{ steps.changelog.outputs.changelog }}"
