name: "Release Manager [Dispatch]"

on:
  workflow_dispatch:
    inputs:
      merge:
        type: boolean
        description: 'Merge release branch'
        default: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  get-pr:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.get_pr.outputs.pr_number }}
    steps:
      - uses: actions/checkout@v4
      # headがrelease/かつopenのPRを1つ取得
      - name: Get PRs
        run: |
          echo "pr_number=$(gh pr list --limit 1 --search "head:release/ is:open" --json number  --jq '.[] | .number')" >> $GITHUB_OUTPUT
        id: get_pr

  merge:
    uses: ./.github/workflows/merge.yml
    needs: Checkout PR
    if: ${{ needs.get-pr.outputs.pr_number != '' && inputs.merge == true }}
    with:
      pr_number: ${{ needs.get-pr.outputs.pr_number }}
      main: ${{ github.ref_name }}
      user: LuckyBeast

  create-prerelease:
    uses: ./.github/workflows/create-prerelease.yml
    needs: get-pr
    if: ${{ needs.get-pr.outputs.pr_number != '' && inputs.merge != true  }}
    with:
      pr_number: ${{ needs.get-pr.outputs.pr_number }}
      user: LuckyBeast

  create-target:
    uses: ./.github/workflows/create-target.yml
    needs: get-pr
    if: ${{ needs.get-pr.outputs.pr_number == '' }}
    with:
      user: LuckyBeast
