on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: "Release Manager"

jobs:
  get-prs:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.get_prs.outputs.pr_number }}
    steps:
      - uses: actions/checkout@v4
      # headがrelease/かつopenのPRを1つ取得
      - name: Get PRs
        run: |
          echo "pr_number=$(gh pr list --limit 1 --search "head:release/ is:open" --json number  --jq '.[] | .number')" >> $GITHUB_OUTPUT
        id: get_prs

  dispatch-prerelease:
    uses: ./.github/workflows/dispatch-prerelease.yml
    permissions:
      contents: write
      issues: write
      pull-requests: write
    needs: get-prs
    if: ${{ needs.get-prs.outputs.pr_number != '' }}
    with:
      pr_number: ${{ needs.get-prs.outputs.pr_number }}
      user: 'LuckyBeast'

  create-target:
    uses: ./.github/workflows/create-target.yml
    permissions:
      contents: write
      issues: write
      pull-requests: write
    needs: get-prs
    if: ${{ needs.get-prs.outputs.pr_number == '' }}
    with:
      user: 'LuckyBeast'
