name: "Release Manager: release RC when ready for review"

on:
  pull_request:
    types: [ready_for_review]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.get_pr.outputs.ref }}
    steps:
      - uses: actions/checkout@v4
      # PR情報を取得
      - name: Get PR
        run: |
          pr_json=$(gh pr view ${{ github.event.pull_request.number }} --json isDraft,headRefName)
          echo "ref=$(echo $pr_json | jq -r '.headRefName')" >> $GITHUB_OUTPUT
        id: get_pr
  release:
    uses: ./.github/workflows/dispatch-prerelease.yml
    needs: check
    if: startsWith(needs.check.outputs.ref, 'release/')
    with:
      pr_number: ${{ github.event.pull_request.number }}
      user: 'LuckyBeast'
